# SPDX-License-Identifier: PMPL-1.0-or-later
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Idea
      description: Describe your idea
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Why would this be useful?
