# SPDX-License-Identifier: PMPL-1.0-or-later
labels: [question]
body:
  - type: textarea
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Context
      description: Any relevant background
