# SPDX-License-Identifier: PMPL-1.0-or-later
# Bug report issue template for {{OWNER}}/{{REPO}}
name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "priority: unset", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please fill out the sections below
        so we can reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: When I do X, Y happens instead of Z.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: I expected X to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened instead.
      placeholder: Instead, Y happened.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or logs
      description: If applicable, add screenshots or paste error logs to help explain the problem.
      placeholder: Paste screenshots or error output here.
      render: text
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low (cosmetic, minor inconvenience)
        - Medium (functionality impaired but workaround exists)
        - High (major functionality broken)
        - Critical (data loss, security issue, complete failure)
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      description: What OS are you using?
      placeholder: "e.g. Fedora 43, macOS 15.3, Windows 11"
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of this project are you using?
      placeholder: "e.g. 1.2.3, commit abc1234, main branch"
    validations:
      required: false

  - type: input
    id: runtime
    attributes:
      label: Runtime / toolchain
      description: Relevant runtime or toolchain version, if applicable.
      placeholder: "e.g. Deno 2.1, Rust nightly 2026-02-10, Gleam 1.8"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Any other relevant information.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I am using a supported version of this project
          required: false
        - label: I would be willing to submit a PR to fix this
          required: false
